### ISSUE TITLE
1.15 Cant attack non hostile mobs and proud soul doesnt stack

### ISSUE THREAD

**Issue by Grimlorc** [flammpfeil/SlashBlade_2#4]
Mods version: Slash blade 1.15-0.0.2

Problem : 
-Cant attack non hostile mobs, but can attack after u punch it or hurt it by another tools
-Proud Soul doesnt stack

**Comment by iceyrazor** [comment]
as long as ive known it. slashblade has been a PvE mod only, and only is ment to work on hostile mobs.
you can still left click hit though
